### ISSUE TITLE
Unable to find an entry point named 'Vad_Process' in DLL 'WebRtcVad.dll'

### ISSUE THREAD

**Issue by ladenedge** [ladenedge/WebRtcVadSharp#1]
On x86 builds, the C# DLL is looking for an entry point that is not available in the C DLL.

```
System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'Vad_Process' in DLL 'WebRtcVad.dll'.
  Source=WebRtcVadSharp
  StackTrace:
   at WebRtcVadSharp.WebRtc.WebRtcDll.NativeMethods.Vad_Process(IntPtr handle, Int32 fs, Int16[] audio_frame, Int64 frame_length)
   at WebRtcVadSharp.WebRtc.WebRtcDll.Process(IntPtr handle, Int32 fs, Int16[] audio_frame, Int64 frame_length)
   at WebRtcVadSharp.WebRtcVad.HasSpeech(Int16[] audioFrame, SampleRate sampleRate, FrameLength frameLength)
   at WebRtcVadSharp.WebRtcVad.HasSpeech(Int16[] audioFrame)
   at ConsoleApp1.Program.Main(String[] _) in C:\Users\laden\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 12
```

According to Dependency Walker, the names are mangled with an unexpected calling convention:

![image](https://user-images.githubusercontent.com/2699775/85878127-7807ab00-b795-11ea-836a-09a4a7eb3903.png)

**Comment by ladenedge** [comment]
Fixed in [v1.2.1](/ladenedge/WebRtcVadSharp/releases/tag/1.2.1).
